services:
  spa_db:
    image: mysql:8
    container_name: spa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: spa_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  spa_app:
    build: .
    container_name: spa_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: spa_db
      DB_USER: root
      DB_PASSWORD: 12345
      DB_NAME: spa_db
    depends_on:
      - spa_db

volumes:
  mysql_data:
